# deprecated ...
version: '3'
services:
  postgres-container:
    image: postgres:15
    container_name: suggestmovies
    environment:
      POSTGRES_DB: suggestmovies
      POSTGRES_USER: suggestmovies
      POSTGRES_PASSWORD: suggestmovies
    volumes:
      - ./postgres_orchestrator_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
